import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, BrainCircuit, FileSearch, Image, MessageSquareText, PlugZap, ShieldCheck, SlidersHorizontal, Sparkles, Wrench } from 'lucide-react';

const tools = [
  { icon: BrainCircuit, title: 'Behavioral analysis', state: 'Enabled', tone: 'text-[#2fd9c7]', description: 'Lets the agent summarize approved context and identify resilience signals without exposing hidden reasoning.' },
  { icon: FileSearch, title: 'Context intelligence', state: 'Enabled', tone: 'text-[#8bbcff]', description: 'Indexes campaign-provided documents so planning stays grounded in the workspace context.' },
  { icon: MessageSquareText, title: 'Scenario composer', state: 'Review required', tone: 'text-[#f6bf5c]', description: 'Drafts authorized awareness scenarios and keeps final execution behind operator review and scope checks.' },
  { icon: Image, title: 'Simulation media', state: 'Guardrailed', tone: 'text-[#a78bfa]', description: 'Prepares non-deceptive training and simulation assets with provenance and approval requirements.' },
];

export default function AgentTools() {
  return <main className="relative min-h-screen overflow-hidden bg-[#090b10] px-4 py-6 text-[#f5f7fb] sm:px-6 lg:px-8">
    <div className="pointer-events-none absolute inset-0 py-grid-signal opacity-45" />
    <div className="pointer-events-none absolute left-1/2 top-[-22rem] h-[44rem] w-[44rem] -translate-x-1/2 rounded-full bg-[#ff4757]/[.055] blur-[140px]" />
    <div className="relative mx-auto max-w-[1280px]">
      <Link to="/dashboard" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-[#7f8a98] transition hover:text-white"><ArrowLeft className="h-3.5 w-3.5" /> Back to command home</Link>
      <section className="py-command-hero relative mt-5 overflow-hidden px-6 py-8 sm:px-9 sm:py-10">
        <div className="absolute right-5 top-4 font-mono text-[9px] uppercase tracking-[.22em] text-[#67717e]">Capability registry / 04 modules</div>
        <div className="flex max-w-3xl items-start gap-5"><span className="flex h-12 w-12 shrink-0 items-center justify-center border border-[#ff4757]/30 bg-[#ff4757]/10 text-[#ff7180]"><Wrench className="h-5 w-5" /></span><div><div className="font-mono text-[10px] uppercase tracking-[.2em] text-[#ff7782]">Agent configuration</div><h1 className="mt-3 text-4xl font-black tracking-[-.06em] sm:text-6xl">Choose what the agent can use.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#98a4b3]">Tools are campaign capabilities—not hidden autonomous powers. Configure what is available, what requires review, and what remains outside the agent's scope.</p></div></div>
      </section>

      <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_320px]">
        <section className="grid gap-4 sm:grid-cols-2">{tools.map(({ icon: Icon, title, state, tone, description }) => <article key={title} className="py-command-card group relative overflow-hidden p-5 transition hover:border-white/[.14]"><div className="absolute right-0 top-0 h-16 w-16 border-l border-b border-white/[.04]" /><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center border border-white/[.08] bg-white/[.025] ${tone}`}><Icon className="h-4 w-4" /></span><span className="border border-white/[.08] px-2 py-1 font-mono text-[8px] uppercase tracking-[.15em] text-[#8792a0]">{state}</span></div><h2 className="mt-6 text-lg font-black tracking-[-.035em]">{title}</h2><p className="mt-2 text-xs leading-5 text-[#788493]">{description}</p><button className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-[#c7d0da] transition hover:text-white">Configure <ArrowUpRight className="h-3.5 w-3.5" /></button></article>)}</section>
        <aside className="space-y-5"><article className="py-command-card p-5"><div className="flex items-center gap-2 text-sm font-black"><SlidersHorizontal className="h-4 w-4 text-[#2fd9c7]" /> Campaign defaults</div><p className="mt-3 text-xs leading-5 text-[#778392]">These defaults determine which capabilities the agent can propose. Individual campaigns can narrow them, never silently expand them.</p><div className="mt-5 space-y-3"><div className="flex items-center justify-between border-t border-white/[.07] pt-3 text-xs"><span className="text-[#8d98a7]">Plan approval</span><span className="text-[#58e6a0]">Required</span></div><div className="flex items-center justify-between border-t border-white/[.07] pt-3 text-xs"><span className="text-[#8d98a7]">Context provenance</span><span className="text-[#58e6a0]">Tracked</span></div><div className="flex items-center justify-between border-t border-white/[.07] pt-3 text-xs"><span className="text-[#8d98a7]">Stop conditions</span><span className="text-[#58e6a0]">Enforced</span></div></div></article>
        <Link to="/settings/integrations" className="py-command-card group block p-5"><PlugZap className="h-5 w-5 text-[#2fd9c7]" /><h2 className="mt-4 font-black">Connections are separate.</h2><p className="mt-2 text-xs leading-5 text-[#778392]">Configure approved channel adapters and model infrastructure in Connections. A tool does not automatically grant delivery access.</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-[#2fd9c7]">Open connections <ArrowUpRight className="h-3.5 w-3.5" /></span></Link>
        <div className="border border-[#2fd9c7]/15 bg-[#2fd9c7]/[.035] p-5"><div className="flex items-center gap-2 text-xs font-bold text-[#cfe8e5]"><ShieldCheck className="h-4 w-4 text-[#2fd9c7]" /> Guardrail model</div><p className="mt-2 text-xs leading-5 text-[#7f9a98]">The agent can assist with planning and analysis inside authorized simulations. Sensitive actions remain observable and subject to scope and operator controls.</p></div></aside>
      </div>
      <div className="mt-5 border border-white/[.08] bg-[#0c0f15] px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Sparkles className="h-4 w-4 text-[#ff7180]" /><div><div className="text-xs font-bold">Tool registry, not a tactics marketplace</div><div className="mt-1 text-[11px] text-[#687483]">Capabilities are designed around analysis, simulation governance and approved training workflows.</div></div></div><Link to="/campaigns/new" className="border border-[#ff4757]/30 bg-[#ff4757]/10 px-3 py-2 text-xs font-bold text-[#ff8b95]">Use in a campaign →</Link></div></div>
    </div>
  </main>;
}
