import { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowLeft, Bot, BrainCircuit, Check, ChevronRight, FileSearch,
  Globe2, Image, Mail, MessageCircle, Mic, Plug, ShieldCheck, Sparkles,
} from 'lucide-react';

type Tool = { id: string; name: string; description: string; icon: typeof Bot; group: string; enabled: boolean; tone: string };

const initialTools: Tool[] = [
  { id: 'context', name: 'Context analysis', description: 'Read approved campaign context and organize facts, constraints, and open questions.', icon: FileSearch, group: 'Planning', enabled: true, tone: 'text-[#68eadc]' },
  { id: 'planner', name: 'Adaptive planner', description: 'Propose campaign branches and operator-review checkpoints as new simulated responses arrive.', icon: BrainCircuit, group: 'Planning', enabled: true, tone: 'text-[#a78bfa]' },
  { id: 'content', name: 'Content studio', description: 'Draft simulation-safe messages and supporting assets for review before use.', icon: Sparkles, group: 'Creative', enabled: true, tone: 'text-[#f5c969]' },
  { id: 'image', name: 'Image workspace', description: 'Prepare visual assets for approved simulation scenarios and learning material.', icon: Image, group: 'Creative', enabled: false, tone: 'text-[#ff8994]' },
  { id: 'mail', name: 'Mail adapter', description: 'Use a configured email integration inside campaigns that explicitly allow email.', icon: Mail, group: 'Channels', enabled: true, tone: 'text-[#68eadc]' },
  { id: 'messaging', name: 'Messaging adapter', description: 'Use configured messaging channels only within approved simulation scope and stop conditions.', icon: MessageCircle, group: 'Channels', enabled: true, tone: 'text-[#68eadc]' },
  { id: 'voice', name: 'Voice adapter', description: 'Support approved voice exercise workflows through a configured provider.', icon: Mic, group: 'Channels', enabled: false, tone: 'text-[#ff8994]' },
  { id: 'research', name: 'Campaign research', description: 'Help the operator identify gaps in the supplied campaign context without inventing target facts.', icon: Globe2, group: 'Analysis', enabled: false, tone: 'text-[#a78bfa]' },
];

export default function AgentTools() {
  const [tools, setTools] = useState(initialTools);
  const toggle = (id: string) => setTools(current => current.map(tool => tool.id === id ? { ...tool, enabled: !tool.enabled } : tool));
  const groups = [...new Set(tools.map(tool => tool.group))];
  const enabled = tools.filter(tool => tool.enabled).length;

  return <main className="relative min-h-screen overflow-hidden bg-[#07090d] px-5 py-6 text-[#f5f7fb] sm:px-8 lg:px-12">
    <div className="pointer-events-none absolute inset-0 py-grid-signal opacity-40" /><div className="pointer-events-none absolute right-[10%] top-[-15rem] h-[38rem] w-[38rem] rounded-full bg-[#ff263d]/[.05] blur-[140px]" />
    <div className="relative mx-auto max-w-[1320px]">
      <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/[.08] pb-6"><div className="flex items-center gap-4"><Link to="/dashboard" className="flex h-10 w-10 items-center justify-center border border-white/[.1] text-[#9ca6b4] transition hover:border-[#ff4757]/40 hover:text-white"><ArrowLeft className="h-4 w-4" /></Link><div><div className="font-mono text-[9px] uppercase tracking-[.24em] text-[#ff6a76]">Agent capabilities / control plane</div><h1 className="mt-1 text-2xl font-black tracking-[-.04em]">Configure what the agent can use.</h1></div></div><Link to="/settings/integrations" className="inline-flex items-center gap-2 border border-[#ff4757]/30 px-4 py-2.5 text-xs font-bold text-[#ff8994] transition hover:bg-[#ff4757]/10"><Plug className="h-4 w-4" /> Manage plugins <ChevronRight className="h-3.5 w-3.5" /></Link></header>

      <section className="mt-7 grid gap-4 lg:grid-cols-[1fr_320px]"><div><div className="border border-white/[.09] bg-[#0b0d12]/85 p-6"><div className="flex items-start gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center border border-[#ff4757]/25 bg-[#ff4757]/10 text-[#ff6a76]"><Bot className="h-6 w-6" /></span><div><h2 className="text-lg font-bold">Tools are permissions, not personality.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#8b96a5]">Enable the capabilities available to PhishYou during campaign work. Integrations provide the underlying adapters; each campaign can still narrow scope, require review, or disable a tool entirely.</p></div></div></div>
        <div className="mt-5 space-y-7">{groups.map(group => <section key={group}><div className="mb-3 flex items-center gap-3"><div className="font-mono text-[10px] uppercase tracking-[.22em] text-[#68717d]">{group}</div><div className="h-px flex-1 bg-white/[.07]" /></div><div className="grid gap-3 md:grid-cols-2">{tools.filter(tool => tool.group === group).map(tool => { const Icon = tool.icon; return <article key={tool.id} className={`relative border p-5 transition ${tool.enabled ? 'border-white/[.12] bg-white/[.025]' : 'border-white/[.07] bg-black/[.12] opacity-75'}`}><div className="flex items-start justify-between gap-4"><span className={`flex h-10 w-10 items-center justify-center border border-white/[.08] bg-black/20 ${tool.tone}`}><Icon className="h-5 w-5" /></span><button type="button" onClick={() => toggle(tool.id)} className={`relative h-6 w-11 border transition ${tool.enabled ? 'border-[#2fd9c7]/45 bg-[#2fd9c7]/15' : 'border-white/[.14] bg-white/[.03]'}`} aria-pressed={tool.enabled}><span className={`absolute top-1 h-3.5 w-3.5 transition ${tool.enabled ? 'right-1 bg-[#2fd9c7]' : 'left-1 bg-[#596270]'}`} /></button></div><h3 className="mt-4 text-sm font-bold">{tool.name}</h3><p className="mt-2 text-xs leading-5 text-[#7e8998]">{tool.description}</p><div className="mt-4 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.15em]"><span className={`h-1.5 w-1.5 ${tool.enabled ? 'bg-[#2fd9c7]' : 'bg-[#596270]'}`} />{tool.enabled ? 'Available to agent' : 'Disabled'}</div></article>})}</div></section>)}</div></div>
        <aside className="space-y-4"><div className="border border-[#ff4757]/20 bg-[#0b0d12]/90 p-5"><div className="font-mono text-[9px] uppercase tracking-[.2em] text-[#ff8994]">Current capability set</div><div className="mt-4 text-5xl font-black tracking-[-.06em]">{enabled}<span className="text-xl text-[#68717d]">/{tools.length}</span></div><p className="mt-2 text-xs leading-5 text-[#7e8998]">Capabilities enabled at the workspace level.</p></div><div className="border border-white/[.08] bg-white/[.02] p-5"><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="h-4 w-4 text-[#68eadc]" /> Campaign guardrails</div><ul className="mt-4 space-y-3 text-xs leading-5 text-[#8792a0]"><li className="flex gap-2"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#2fd9c7]" />Campaign scope can override these tools.</li><li className="flex gap-2"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#2fd9c7]" />Operator review can be required before actions.</li><li className="flex gap-2"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#2fd9c7]" />Simulation channels remain tied to configured adapters.</li></ul></div><div className="border border-white/[.08] bg-white/[.015] p-5"><div className="font-mono text-[9px] uppercase tracking-[.2em] text-[#68717d]">Need an adapter?</div><p className="mt-2 text-xs leading-5 text-[#7e8998]">Connect or configure providers separately, then expose only the capabilities you want the agent to see.</p><Link to="/settings/integrations" className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[#ff8994]">Open integrations <ChevronRight className="h-3.5 w-3.5" /></Link></div></aside>
      </section>
    </div>
  </main>;
}
