import { BrainCircuit, FileSearch, Image, MessageSquareText, ShieldCheck, SlidersHorizontal, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

const tools=[
 {icon:BrainCircuit,name:'Behavior intelligence',desc:'Turns approved campaign context into adaptive, reviewable scenario recommendations.',state:'Enabled',tone:'ready'},
 {icon:FileSearch,name:'Context intelligence',desc:'Indexes campaign briefs and approved knowledge packs for grounded planning.',state:'Enabled',tone:'ready'},
 {icon:MessageSquareText,name:'Scenario composer',desc:'Builds multi-turn authorized awareness simulations and debrief material.',state:'Review required',tone:'review'},
 {icon:Image,name:'Simulation media',desc:'Creates campaign assets for approved training scenarios and operator review.',state:'Guardrailed',tone:'guard'},
];
export default function AgentTools(){return <div className="py-page"><section className="py-page-intro"><p className="py-eyebrow">AGENT CAPABILITIES</p><h1 className="py-title">Tools the agent can use.</h1><p className="py-lede">Configure the intelligence available to PhishYou. Capabilities remain campaign-scoped and subject to your organization’s controls.</p></section><section className="py-tool-hero py-surface"><div><span className="py-kicker"><Sparkles size={14}/> CAPABILITY LAYER</span><h2>Give the agent the right instruments.</h2><p>Enable intelligence, set guardrails, and keep human review exactly where your security program requires it.</p></div><Link className="py-primary" to="/settings">Open controls <SlidersHorizontal size={16}/></Link></section><section className="py-dashboard-section"><div className="py-section-heading"><div><p className="py-eyebrow">AVAILABLE</p><h2>Capability library</h2></div><span className="py-count">{tools.length} TOOLS</span></div><div className="py-grid py-tools-grid">{tools.map(({icon:Icon,name,desc,state,tone})=><article className="py-tool-card py-card" key={name}><div className="py-tool-icon"><Icon size={21}/></div><div className="py-tool-card-head"><h3>{name}</h3><span className={'py-state '+tone}>{state}</span></div><p>{desc}</p><button className="py-text-action">Configure capability <span>→</span></button></article>)}</div></section><section className="py-safety-strip"><ShieldCheck size={20}/><div><strong>Operator controls stay in the loop.</strong><span>Tool access is configured independently from external connections and campaign activity.</span></div><Link to="/settings/integrations">Manage connections →</Link></section></div>}
