import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { Activity, Bot, BrainCircuit, CheckCircle2, ChevronRight, FileText, MessageCircle, Pause, Play, ShieldCheck, Sparkles, Waypoints } from 'lucide-react';

const trace = [
  { time: '09:42:11', title: 'Context indexed', text: 'Approved exercise brief and policy constraints loaded into the campaign workspace.', state: 'done' },
  { time: '09:42:14', title: 'Scope check', text: 'Channels and target cohort validated against the campaign guardrails.', state: 'done' },
  { time: '09:42:21', title: 'Plan generation', text: 'Agent is drafting branches and stop conditions for operator review.', state: 'active' },
  { time: '—', title: 'Simulation execution', text: 'Starts only after approval. Live events remain observable and auditable.', state: 'queued' },
];

const conversations = [
  { name: 'Participant A', channel: 'Approved chat simulator', status: 'Active', preview: 'The simulation adapter is waiting for the next approved branch…' },
  { name: 'Participant B', channel: 'Email simulator', status: 'Review', preview: 'Agent requested an operator decision before continuing.' },
  { name: 'Participant C', channel: 'Training sandbox', status: 'Complete', preview: 'Debrief queued after the exercise outcome was recorded.' },
];

export default function CampaignWorkspace() {
  const { id = 'demo-workspace' } = useParams();
  const [tab, setTab] = useState<'overview' | 'agent' | 'conversations'>('overview');
  const [running, setRunning] = useState(true);

  return <main className="relative min-h-screen overflow-hidden bg-[#090b10] px-4 py-5 text-[#f5f7fb] sm:px-6 lg:px-8">
    <div className="pointer-events-none absolute inset-0 py-grid-signal opacity-45" />
    <div className="pointer-events-none absolute right-[-10rem] top-[-14rem] h-[36rem] w-[36rem] rounded-full bg-[#ff4757]/[.055] blur-[130px]" />
    <div className="relative mx-auto max-w-[1540px]">
      <header className="border border-white/[.08] bg-[#0c0f15]/90 px-5 py-5 backdrop-blur-xl sm:px-6">
        <div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.2em] text-[#ff6a76]"><span className={`h-2 w-2 rounded-full ${running ? 'bg-[#ff4757] py-status-dot' : 'bg-[#7a8595]'}`} /> Campaign intelligence / {id}</div><h1 className="mt-2 text-3xl font-black tracking-[-.05em] sm:text-4xl">Q3 verification awareness exercise</h1><p className="mt-2 text-sm text-[#7a8595]">One campaign. One context. One observable agent workspace.</p></div><div className="flex flex-wrap gap-3"><div className="border border-[#2fd9c7]/15 bg-[#2fd9c7]/[.04] px-4 py-2 text-xs"><span className="font-mono text-[9px] uppercase tracking-[.16em] text-[#2fd9c7]">Safety</span><div className="mt-1 font-semibold">Scope locked</div></div><button onClick={() => setRunning((value) => !value)} className="inline-flex items-center gap-2 border border-[#ff4757]/35 bg-[#ff4757] px-4 py-2.5 text-xs font-black uppercase tracking-[.12em] text-[#170508]">{running ? <><Pause className="h-4 w-4" /> Pause</> : <><Play className="h-4 w-4" /> Resume</>}</button></div></div>
        <nav className="mt-6 flex gap-1 overflow-x-auto border-t border-white/[.06] pt-4">{([['overview','Overview'],['agent','Agent trace'],['conversations','Conversations']] as const).map(([value,label]) => <button key={value} onClick={() => setTab(value)} className={`px-4 py-2 text-xs font-bold uppercase tracking-[.12em] transition ${tab === value ? 'border border-[#ff4757]/30 bg-[#ff4757]/[.07] text-[#ff8a93]' : 'text-[#7a8595] hover:text-white'}`}>{label}</button>)}</nav>
      </header>

      {tab === 'overview' && <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_360px]">
        <section className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Campaign state', running ? 'ACTIVE' : 'PAUSED', Activity],['Participants', '12', ShieldCheck],['Agent branches', '08', BrainCircuit],['Signals reviewed', '47', Sparkles]].map(([label,value,Icon]) => { const I = Icon as typeof Activity; return <article key={label as string} className="py-command-card border border-white/[.08] p-5"><I className="h-5 w-5 text-[#ff6a76]" /><div className="mt-5 text-3xl font-black tracking-[-.05em]">{value as string}</div><div className="mt-1 text-xs text-[#7a8595]">{label as string}</div></article>})}</div>
          <section className="py-command-card border border-white/[.08] p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#ff6a76]">Agent plan</div><h2 className="mt-1 text-xl font-bold">Decision path, not a black box.</h2></div><Waypoints className="h-5 w-5 text-[#2fd9c7]" /></div><div className="mt-6 grid gap-3 md:grid-cols-4">{['Context → scope', 'Question → plan', 'Review → approve', 'Observe → debrief'].map((item,index) => <div key={item} className="relative border border-white/[.07] bg-black/20 p-4"><span className="font-mono text-[9px] text-[#ff6a76]">0{index+1}</span><p className="mt-5 text-sm font-semibold">{item}</p>{index < 3 && <ChevronRight className="absolute -right-3 top-1/2 hidden h-5 w-5 text-[#ff4757] md:block" />}</div>)}</div><button onClick={() => setTab('agent')} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#2fd9c7]">Inspect agent trace <ArrowIcon /></button></section>
          <section className="py-command-card border border-white/[.08] p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#7a8595]">Campaign conversations</div><h2 className="mt-1 text-xl font-bold">Live simulation surfaces</h2></div><MessageCircle className="h-5 w-5 text-[#ff6a76]" /></div><div className="mt-5 divide-y divide-white/[.06] border-y border-white/[.06]">{conversations.map((conversation) => <button key={conversation.name} onClick={() => setTab('conversations')} className="flex w-full items-center gap-4 px-1 py-4 text-left transition hover:bg-white/[.02]"><span className="flex h-9 w-9 items-center justify-center border border-white/[.08] text-[#a8b4c4]"><Bot className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{conversation.name}</span><span className="block truncate text-xs text-[#7a8595]">{conversation.preview}</span></span><span className="border border-white/[.08] px-2 py-1 font-mono text-[9px] text-[#a8b4c4]">{conversation.status}</span></button>)}</div></section>
        </section>
        <aside className="space-y-5"><section className="border border-[#ff4757]/20 bg-[#ff4757]/[.035] p-5"><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.18em] text-[#ff8a93]"><ShieldCheck className="h-4 w-4" /> Campaign guardrails</div><div className="mt-5 space-y-4 text-sm text-[#a8b4c4]"><div><span className="block text-white">Consent</span><span className="text-xs text-[#7a8595]">Verified before any simulation starts</span></div><div><span className="block text-white">Secrets</span><span className="text-xs text-[#7a8595]">Simulation tokens only — no live OTPs or credentials</span></div><div><span className="block text-white">Stop conditions</span><span className="text-xs text-[#7a8595]">Agent pauses for distress or policy boundaries</span></div></div></section><section className="py-command-card border border-white/[.08] p-5"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#7a8595]">Context inventory</div><div className="mt-4 space-y-3">{['Exercise brief.pdf','Channel approval.md','Synthetic persona notes.txt'].map((file) => <div key={file} className="flex items-center gap-3 border border-white/[.06] bg-black/20 px-3 py-3"><FileText className="h-4 w-4 text-[#ff6a76]" /><span className="truncate text-xs text-[#a8b4c4]">{file}</span></div>)}</div></section></aside>
      </div>}

      {tab === 'agent' && <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_380px]"><div className="py-command-card border border-white/[.08] p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center border border-[#ff4757]/25 bg-[#ff4757]/[.06] text-[#ff6a76]"><BrainCircuit className="h-5 w-5" /></span><div><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#ff6a76]">Reasoning surface</div><h2 className="text-xl font-bold">Planning and action trace</h2></div></div><div className="mt-8 space-y-0">{trace.map((item,index) => <div key={item.title} className="relative flex gap-5 pb-8 last:pb-0"><div className="flex flex-col items-center"><span className={`mt-1 h-3 w-3 rounded-full ${item.state === 'active' ? 'bg-[#ff4757] shadow-[0_0_18px_rgba(255,71,87,.85)]' : item.state === 'done' ? 'bg-[#2fd9c7]' : 'border border-[#5a6470] bg-transparent'}`} />{index < trace.length-1 && <span className="mt-2 h-full w-px bg-white/[.08]" />}</div><div className="flex-1 border border-white/[.06] bg-black/15 p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-bold">{item.title}</h3><span className="font-mono text-[9px] text-[#5a6470]">{item.time}</span></div><p className="mt-2 text-sm leading-6 text-[#7a8595]">{item.text}</p></div></div>)}</div></div><aside className="border border-white/[.08] bg-black/15 p-5"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#7a8595]">Agent status</div><div className="mt-5 border border-[#2fd9c7]/15 bg-[#2fd9c7]/[.04] p-4"><div className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 className="h-4 w-4 text-[#2fd9c7]" /> Plan stays reviewable</div><p className="mt-2 text-xs leading-5 text-[#7a8595]">Operators can inspect the campaign path and safety constraints without exposing hidden chain-of-thought.</p></div></aside></section>}

      {tab === 'conversations' && <section className="mt-5 grid gap-5 xl:grid-cols-[300px_1fr_320px]"><aside className="border border-white/[.08] bg-black/15 p-3">{conversations.map((conversation,index) => <button key={conversation.name} className={`mb-2 w-full border p-4 text-left ${index === 0 ? 'border-[#ff4757]/30 bg-[#ff4757]/[.045]' : 'border-white/[.06] hover:bg-white/[.025]'}`}><div className="text-sm font-bold">{conversation.name}</div><div className="mt-1 text-xs text-[#7a8595]">{conversation.channel}</div></button>)}</aside><section className="py-command-card border border-white/[.08] p-5 sm:p-6"><div className="flex items-center justify-between border-b border-white/[.07] pb-4"><div><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#ff6a76]">Simulation conversation</div><h2 className="mt-1 text-lg font-bold">Participant A · approved sandbox</h2></div><span className="border border-[#2fd9c7]/20 bg-[#2fd9c7]/[.05] px-2 py-1 text-[10px] text-[#2fd9c7]">SIMULATED</span></div><div className="space-y-4 py-6"><div className="max-w-[78%] border border-white/[.08] bg-white/[.025] p-4 text-sm text-[#a8b4c4]">A simulation message would render here through the approved channel adapter.</div><div className="ml-auto max-w-[78%] border border-[#ff4757]/20 bg-[#ff4757]/[.045] p-4 text-sm text-[#d8dee8]">Participant response preview is redacted and evaluated against the campaign's learning objective.</div><div className="max-w-[78%] border border-white/[.08] bg-white/[.025] p-4 text-sm text-[#a8b4c4]">The agent selected the next safe branch and requested operator approval.</div></div><div className="border-t border-white/[.07] pt-4 text-xs text-[#7a8595]">Live conversations are observable here; production delivery remains subject to channel approval and campaign guardrails.</div></section><aside className="border border-white/[.08] bg-black/15 p-5"><div className="font-mono text-[9px] uppercase tracking-[.18em] text-[#7a8595]">Current branch</div><h3 className="mt-3 text-lg font-bold">Verification behavior</h3><p className="mt-2 text-sm leading-6 text-[#a8b4c4]">Measure whether the participant follows the approved verification process under simulated pressure.</p><div className="mt-5 space-y-3 border-t border-white/[.06] pt-4 text-xs text-[#7a8595]"><div>Signal: <span className="text-white">Awaiting response</span></div><div>Stop condition: <span className="text-white">Immediate pause on distress</span></div><div>Outcome: <span className="text-white">Debrief and learning</span></div></div></aside></section>}
    </div>
  </main>;
}

function ArrowIcon() { return <ChevronRight className="h-4 w-4" />; }
