import { FormEvent, useState } from 'react';
import { ArrowUp, Bot, BrainCircuit, Cable, FileText, Plus, Sparkles, Workflow } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

const campaigns=[
 {id:'finance-q3',name:'Finance resilience / Q3',state:'Agent planning',detail:'Context indexed · 3 review questions'},
 {id:'onboarding',name:'New-hire verification exercise',state:'Ready for review',detail:'Plan generated · operator approval required'},
 {id:'leadership',name:'Leadership awareness cycle',state:'Observing',detail:'After-action intelligence available'},
];
const tools=[{icon:BrainCircuit,name:'Behavior intelligence',note:'Available to approved campaigns'},{icon:Workflow,name:'Scenario composition',note:'Plans and checkpoints'},{icon:Cable,name:'Connected channels',note:'Configure approved adapters'}];

export default function Dashboard(){const navigate=useNavigate();const [prompt,setPrompt]=useState('');const [submitted,setSubmitted]=useState('');const ask=(e:FormEvent)=>{e.preventDefault();const value=prompt.trim();if(!value)return;setSubmitted(value);setPrompt('')};return <div className="agent-home"><header className="topline"><div><div className="eyebrow">Agent workspace</div><h1 className="display">Good morning, operator.</h1></div><div className="topline-actions"><Link className="button-secondary" to="/settings/integrations">Configure connections</Link><Link className="button-primary" to="/campaigns/new"><Plus size={17}/> New campaign</Link></div></header>
<section className="agent-stage"><div className="eyebrow">PhishYou intelligence agent</div><h2 className="display">What would you like to work on?</h2><p>Start a campaign, continue an investigation, or ask the agent to help turn your approved context into a reviewable plan.</p><form className="prompt-box" onSubmit={ask}><Bot size={19} color="var(--accent)"/><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask about a campaign, plan, context or next step…"/><button aria-label="Send prompt"><ArrowUp size={18}/></button></form><div className="prompt-chips">{['Start a new campaign','Review a campaign plan','What needs my attention?'].map(x=><button type="button" onClick={()=>setPrompt(x)} key={x}>{x}</button>)}</div>{submitted&&<div style={{marginTop:18,color:'var(--muted)',fontSize:13}}>Request queued for the agent: <b style={{color:'var(--ink)'}}>{submitted}</b></div>}</section>
<div className="workspace-grid"><section className="campaign-list-card panel"><div className="section-head"><div><div className="eyebrow">Your workspaces</div><h3>Campaigns</h3></div><Link to="/campaigns/new" className="button-secondary"><Plus size={15}/> New</Link></div>{campaigns.map(c=><button className="campaign-row" onClick={()=>navigate(`/campaigns/${c.id}`)} key={c.id} style={{width:'100%',background:'transparent',color:'inherit',textAlign:'left',borderLeft:0,borderRight:0,borderBottom:0}}><span className="campaign-pulse"/><div className="grow"><b>{c.name}</b><small>{c.detail}</small></div><div className="campaign-meta">{c.state}</div></button>)}</section><aside className="capability-card panel"><div className="section-head"><div><div className="eyebrow">Agent capabilities</div><h3>What the agent can use</h3></div></div><div className="capability-list">{tools.map(({icon:Icon,name,note})=><Link className="capability" to={name.includes('channel')?'/settings/integrations':'/settings'} key={name}><i><Icon size={17}/></i><div><b>{name}</b><small>{note}</small></div></Link>)}</div><Link to="/settings" style={{display:'inline-flex',gap:8,alignItems:'center',marginTop:18,fontWeight:800,fontSize:13,color:'var(--accent)'}}><Sparkles size={15}/> Manage agent environment</Link></aside></div>
</div>}
