import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Activity, AlertTriangle, ArrowUpRight, Bot, ChevronRight, CircleDot, Command, Loader2, Mail, MessageCircle, Phone, Play, Radar, Search, Send, ShieldAlert, ShieldCheck, Sparkles, Target, Users, X } from 'lucide-react'

type Tier = 'A' | 'B' | 'C'
type Platform = 'email' | 'whatsapp' | 'sms' | 'voice' | 'linkedin' | 'instagram'
interface LiveCampaign { id: string; name: string; targetName: string; platforms: Platform[]; resistanceScore: number; tier: Tier }
interface ActivityEvent { id: string; type: 'campaign_started' | 'campaign_halted' | 'target_defended' | 'target_compromised' | 'harm_detected' | 'admin_action' | 'debrief_delivered'; title: string; description: string; timestamp: string }
interface DashboardData { activeCampaigns: number; tierBreakdown: { A: number; B: number; C: number }; targetsEngaged: { total: number; defended: number; compromised: number; active: number }; humanRiskScore: { score: number; delta: number }; policyGaps: { critical: number; high: number; medium: number }; liveCampaigns: LiveCampaign[]; recentActivity: ActivityEvent[] }

const ago = (minutes: number) => new Date(Date.now() - minutes * 60000).toISOString()
const DEMO: DashboardData = {
  activeCampaigns: 3, tierBreakdown: { A: 1, B: 1, C: 1 }, targetsEngaged: { total: 23, defended: 14, compromised: 6, active: 3 }, humanRiskScore: { score: 42, delta: -12 }, policyGaps: { critical: 2, high: 3, medium: 4 },
  liveCampaigns: [
    { id: 'camp_2026_08_27_001', name: 'Finance Team Payment Verification Q3', targetName: '6 targets · Finance', platforms: ['email', 'whatsapp'], resistanceScore: .68, tier: 'A' },
    { id: 'camp_2026_08_27_002', name: 'HR Onboarding Reset Wave 2', targetName: '4 targets · People Ops', platforms: ['email'], resistanceScore: .31, tier: 'B' },
    { id: 'camp_2026_08_27_003', name: 'Executive Whaling Simulation', targetName: '2 targets · Leadership', platforms: ['voice', 'sms'], resistanceScore: .82, tier: 'A' },
  ],
  recentActivity: [
    { id: '1', type: 'target_compromised', title: 'Credential signal detected', description: 'Finance · simulated portal interaction recorded', timestamp: ago(3) },
    { id: '2', type: 'campaign_started', title: 'Campaign moved live', description: 'Executive Whaling Simulation · Tier A', timestamp: ago(18) },
    { id: '3', type: 'harm_detected', title: 'Safety threshold reached', description: 'Auto-pause triggered for one participant', timestamp: ago(34) },
    { id: '4', type: 'target_defended', title: 'Defensive behavior observed', description: 'Out-of-band verification used before acting', timestamp: ago(52) },
  ],
}
async function fetchDashboard(): Promise<DashboardData> { const c = new AbortController(); const t = window.setTimeout(() => c.abort(), 4000); try { const r = await fetch('/api/v1/organizations/me/dashboard', { headers: { Accept: 'application/json' }, signal: c.signal }); if (!r.ok) throw new Error(); return await r.json() as DashboardData } finally { window.clearTimeout(t) } }
const relativeTime = (iso: string) => { const m = Math.floor((Date.now() - new Date(iso).getTime()) / 60000); return m < 1 ? 'NOW' : m < 60 ? `${m}M` : `${Math.floor(m / 60)}H` }
const icons: Record<Platform, typeof Mail> = { email: Mail, whatsapp: MessageCircle, sms: MessageCircle, voice: Phone, linkedin: MessageCircle, instagram: MessageCircle }
const tierTone: Record<Tier, string> = { A: 'text-[#ff8792] border-[#ff4757]/30 bg-[#ff4757]/[.08]', B: 'text-[#f4bf66] border-[#f59e0b]/30 bg-[#f59e0b]/[.08]', C: 'text-[#6be8a9] border-[#06d369]/30 bg-[#06d369]/[.08]' }

function ThreatRadar({ active }: { active: number }) { return <div className="relative mx-auto aspect-square w-full max-w-[300px] overflow-hidden rounded-full border border-[#ff4757]/20 bg-[radial-gradient(circle_at_center,rgba(255,71,87,.08),transparent_58%)]"><div className="absolute inset-[12%] rounded-full border border-[#ff4757]/15" /><div className="absolute inset-[27%] rounded-full border border-[#ff4757]/15" /><div className="absolute inset-x-0 top-1/2 h-px bg-[#ff4757]/10" /><div className="absolute left-1/2 top-0 h-full w-px bg-[#ff4757]/10" /><div className="absolute inset-0 origin-center animate-[spin_7s_linear_infinite]" style={{ background: 'conic-gradient(from_0deg,transparent 0deg,rgba(255,71,87,.22) 18deg,transparent 60deg)' }} /><span className="absolute left-[22%] top-[30%] h-2 w-2 rounded-full bg-[#2fd9c7] shadow-[0_0_20px_#2fd9c7]" /><span className="absolute right-[18%] top-[42%] h-2 w-2 rounded-full bg-[#ff4757] shadow-[0_0_20px_#ff4757]" /><span className="absolute bottom-[24%] left-[43%] h-2 w-2 rounded-full bg-[#f59e0b] shadow-[0_0_16px_#f59e0b]" /><div className="absolute inset-0 grid place-items-center"><div className="text-center"><div className="font-mono text-5xl font-black text-white">{active}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[.26em] text-[#a87880]">Signals live</div></div></div></div> }
function Stat({ label, value, note, tone = 'text-white' }: { label: string; value: string | number; note: string; tone?: string }) { return <article className="group relative overflow-hidden border border-white/[.08] bg-[#100d10]/80 p-5 transition hover:-translate-y-0.5 hover:border-[#ff4757]/25"><div className="absolute left-0 top-0 h-px w-16 bg-[#ff4757]/60" /><div className="font-mono text-[9px] uppercase tracking-[.2em] text-[#75646a]">{label}</div><div className={`mt-4 text-4xl font-black tracking-[-.06em] ${tone}`}>{value}</div><div className="mt-3 border-t border-white/[.06] pt-3 text-xs text-[#897980]">{note}</div></article> }

export default function Dashboard() {
  const navigate = useNavigate(); const [data, setData] = useState<DashboardData | null>(null); const [fallback, setFallback] = useState(false); const [prompt, setPrompt] = useState(''); const [assistantText, setAssistantText] = useState('Ask about active simulations, human risk, or what needs attention.'); const [assistantOpen, setAssistantOpen] = useState(true)
  const date = useMemo(() => new Intl.DateTimeFormat('en-US', { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date()).toUpperCase(), [])
  useEffect(() => { fetchDashboard().then(setData).catch(() => { setData(DEMO); setFallback(true) }) }, [])
  if (!data) return <div className="grid min-h-[60vh] place-items-center bg-[#09070a]"><Loader2 className="h-8 w-8 animate-spin text-[#ff4757]" /></div>
  const runPrompt = (event?: FormEvent) => { event?.preventDefault(); const q = prompt.trim().toLowerCase(); if (!q) return; if (q.includes('launch') || q.includes('create')) setAssistantText('Campaign creation is not wired in this frontend yet. I can surface the live campaign workspace instead.'); else if (q.includes('risk') || q.includes('attention')) setAssistantText(`${data.policyGaps.critical} critical policy gaps and ${data.targetsEngaged.compromised} compromised simulation outcomes deserve review first.`); else if (q.includes('campaign') || q.includes('active')) setAssistantText(`${data.activeCampaigns} simulations are active. The highest-resistance signal is in ${data.liveCampaigns[2]?.name ?? 'the current campaign set'}.`); else setAssistantText('This command assistant is a UI preview for the future AI layer. It can currently summarize the telemetry already on this screen.'); setPrompt('') }
  const riskTone = data.humanRiskScore.score >= 60 ? 'text-[#ff4757]' : data.humanRiskScore.score >= 30 ? 'text-[#f4bf66]' : 'text-[#2fd9c7]'
  return <main className="min-h-screen bg-[#09070a] px-4 py-4 text-[#f6f1f2] sm:px-6 lg:px-8"><div className="fixed inset-0 pointer-events-none opacity-35" style={{ backgroundImage: 'linear-gradient(rgba(255,71,87,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,71,87,.025) 1px,transparent 1px)', backgroundSize: '48px 48px' }} />
    <div className="relative mx-auto max-w-[1600px]">
      {fallback && <div className="mb-4 flex items-center gap-2 border border-[#f59e0b]/25 bg-[#f59e0b]/[.06] px-4 py-3 font-mono text-[10px] uppercase tracking-[.12em] text-[#f4bf66]"><AlertTriangle className="h-4 w-4" /> Demo telemetry / API channel unavailable</div>}
      <header className="mb-4 flex flex-wrap items-center justify-between gap-4 border-b border-[#ff4757]/15 pb-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center border border-[#ff4757]/35 bg-[#ff4757]/10 text-[#ff6472]"><Command className="h-4 w-4" /></span><div><div className="font-mono text-xs font-black tracking-[.2em]">PHISHYOU// COMMAND</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[.18em] text-[#77656b]">{date} · Authorized intelligence environment</div></div></div><div className="flex items-center gap-3 font-mono text-[9px] uppercase tracking-[.16em] text-[#837279]"><span className="flex items-center gap-2 text-[#2fd9c7]"><CircleDot className="h-3 w-3 animate-pulse" /> System nominal</span><span className="hidden sm:inline">NODE / 01</span></div></header>
      <section className="relative overflow-hidden border border-[#ff4757]/20 bg-[#100b0f] p-6 sm:p-8"><div className="absolute left-0 top-0 h-px w-40 bg-[#ff4757]" /><div className="absolute right-0 top-0 h-20 w-px bg-[#ff4757]/40" /><div className="grid gap-8 lg:grid-cols-[1fr_330px]"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.22em] text-[#ff6f7c]"><span className="h-2 w-2 bg-[#ff4757] shadow-[0_0_16px_#ff4757]" /> Behavioral intelligence layer</div><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[.9] tracking-[-.075em] sm:text-7xl">WHAT SHOULD<br/>WE <span className="text-[#ff4757]">SEE NEXT?</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#98868d]">Your simulations are already producing signals. Use the command layer to explore what changed, where people resisted, and what deserves action.</p>
        <form onSubmit={runPrompt} className="mt-7 max-w-3xl"><div className="group relative flex items-center gap-3 border border-white/[.12] bg-black/30 p-2 shadow-[0_0_0_1px_rgba(255,71,87,.03)] transition focus-within:border-[#ff4757]/60 focus-within:shadow-[0_0_32px_rgba(255,71,87,.09)]"><Bot className="ml-2 h-5 w-5 shrink-0 text-[#ff6472]" /><input value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="Ask PhishYou about your simulations…" className="min-w-0 flex-1 bg-transparent px-1 py-3 text-sm text-white outline-none placeholder:text-[#66565d]" /><button type="submit" className="grid h-10 w-10 place-items-center bg-[#f2eeee] text-[#160d11] transition hover:bg-[#ff4757] hover:text-white" aria-label="Send prompt"><Send className="h-4 w-4" /></button></div><div className="mt-3 flex flex-wrap gap-2">{['What needs attention?', 'Show active campaigns', 'Explain human risk'].map(q => <button key={q} type="button" onClick={() => { setPrompt(q); setTimeout(() => { setAssistantText(q === 'What needs attention?' ? `${data.policyGaps.critical} critical gaps need attention first.` : q === 'Show active campaigns' ? `${data.activeCampaigns} simulations are live across ${data.targetsEngaged.active} currently active participants.` : `Human risk is ${data.humanRiskScore.score}/100, moving ${Math.abs(data.humanRiskScore.delta)} points from the prior period.`) }, 0) }} className="border border-white/[.08] px-3 py-2 font-mono text-[9px] uppercase tracking-[.12em] text-[#a08f95] transition hover:border-[#ff4757]/30 hover:text-[#ff8792]">{q}</button>)}</div></form></div><ThreatRadar active={data.activeCampaigns} /></div></section>
      <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_300px]">
        <div className="min-w-0"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Live campaigns" value={data.activeCampaigns} tone="text-[#2fd9c7]" note={`${data.tierBreakdown.A} high-intensity / ${data.tierBreakdown.B} moderate`} /><Stat label="People engaged" value={data.targetsEngaged.total} note={`${data.targetsEngaged.defended} defensive signals observed`} /><Stat label="Human risk" value={`${data.humanRiskScore.score}`} tone={riskTone} note={`${data.humanRiskScore.delta > 0 ? '+' : ''}${data.humanRiskScore.delta} vs prior period`} /><Stat label="Policy gaps" value={data.policyGaps.critical + data.policyGaps.high} tone="text-[#ff8792]" note={`${data.policyGaps.critical} critical / ${data.policyGaps.high} high`} /></section>
          <section className="mt-4 border border-white/[.08] bg-[#0f0b0e]/90"><div className="flex items-center justify-between border-b border-white/[.07] px-5 py-4"><div><div className="font-mono text-[10px] uppercase tracking-[.2em] text-[#ff8792]">Active simulation matrix</div><h2 className="mt-1 text-lg font-bold">Campaigns in motion</h2></div><span className="font-mono text-[9px] uppercase tracking-[.16em] text-[#74636a]">Live telemetry</span></div><div className="divide-y divide-white/[.06]">{data.liveCampaigns.map((campaign, index) => <article key={campaign.id} className="group grid gap-4 px-5 py-5 transition hover:bg-white/[.025] md:grid-cols-[minmax(0,1fr)_auto_auto] md:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`border px-2 py-1 font-mono text-[9px] font-bold ${tierTone[campaign.tier]}`}>TIER {campaign.tier}</span><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[#6f5f66]">SIM-{String(index + 1).padStart(2, '0')}</span></div><h3 className="mt-3 truncate text-sm font-bold text-[#f0eaec]">{campaign.name}</h3><p className="mt-1 text-xs text-[#837279]">{campaign.targetName}</p></div><div className="flex items-center gap-1">{campaign.platforms.map(platform => { const Icon = icons[platform]; return <span key={platform} className="grid h-8 w-8 place-items-center border border-white/[.08] text-[#8c7a81]"><Icon className="h-3.5 w-3.5" /></span> })}</div><Link to={`/campaigns/${campaign.id}/live`} className="inline-flex items-center gap-2 border border-[#ff4757]/20 px-3 py-2 text-xs font-semibold text-[#d6cdd0] transition hover:border-[#ff4757]/60 hover:bg-[#ff4757]/[.06] hover:text-white">Open live view <ArrowUpRight className="h-3.5 w-3.5" /></Link></article>)}</div></section>
          <section className="mt-4 grid gap-4 lg:grid-cols-2"><div className="border border-white/[.08] bg-[#0f0b0e] p-5"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-[#8c7b81]"><Activity className="h-4 w-4 text-[#2fd9c7]" /> Signal activity</div><div className="mt-5 space-y-4">{data.recentActivity.map(event => <div key={event.id} className="flex gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#ff4757] shadow-[0_0_12px_rgba(255,71,87,.6)]" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><strong className="text-xs text-[#e9e1e4]">{event.title}</strong><span className="font-mono text-[9px] text-[#695a60]">{relativeTime(event.timestamp)}</span></div><p className="mt-1 text-xs leading-5 text-[#817178]">{event.description}</p></div></div>)}</div></div><div className="border border-white/[.08] bg-[#0f0b0e] p-5"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-[#8c7b81]"><ShieldAlert className="h-4 w-4 text-[#ff6472]" /> Attention queue</div><div className="mt-5 space-y-3"><div className="border-l-2 border-[#ff4757] bg-[#ff4757]/[.05] p-3"><strong className="text-xs text-[#ffadb5]">Critical policy gap</strong><p className="mt-1 text-xs text-[#8e7b82]">Review the highest-impact control weakness before escalating simulation intensity.</p></div><div className="border-l-2 border-[#f59e0b] bg-[#f59e0b]/[.04] p-3"><strong className="text-xs text-[#f2c26d]">Safety review queued</strong><p className="mt-1 text-xs text-[#8e7b82]">One simulation crossed a configured attention threshold.</p></div></div></div></section>
        </div>
        {assistantOpen && <aside className="relative h-fit border border-[#ff4757]/20 bg-[#100b0f] xl:sticky xl:top-4"><div className="flex items-center justify-between border-b border-[#ff4757]/15 px-4 py-4"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#ff6472]" /><div className="font-mono text-[10px] uppercase tracking-[.18em] text-[#e7a5ac]">AI command context</div></div><button onClick={() => setAssistantOpen(false)} className="text-[#75646a] hover:text-white" aria-label="Close assistant"><X className="h-4 w-4" /></button></div><div className="p-4"><div className="border border-white/[.07] bg-black/25 p-4"><div className="flex items-center gap-2 text-xs font-bold"><Bot className="h-4 w-4 text-[#2fd9c7]" /> PhishYou intelligence</div><p className="mt-3 text-sm leading-6 text-[#9b888f]">{assistantText}</p></div><div className="mt-4"><div className="font-mono text-[9px] uppercase tracking-[.16em] text-[#706067]">Suggested lenses</div><div className="mt-3 space-y-2">{['Behavior patterns', 'Campaign resistance', 'Control gaps'].map(item => <button key={item} onClick={() => setAssistantText(`${item} will become a deeper AI investigation flow when the intelligence API is connected. For now, this command surface keeps the interaction honest and grounded in visible telemetry.`)} className="flex w-full items-center justify-between border border-white/[.06] px-3 py-3 text-left text-xs text-[#b8aaaf] transition hover:border-[#2fd9c7]/25 hover:bg-[#2fd9c7]/[.03]"><span>{item}</span><ChevronRight className="h-3.5 w-3.5" /></button>)}</div></div><button onClick={() => navigate(`/campaigns/${data.liveCampaigns[0]?.id}/live`)} className="mt-4 flex w-full items-center justify-center gap-2 bg-[#f1eded] px-4 py-3 text-xs font-black text-[#130d10] transition hover:bg-[#ff4757] hover:text-white"><Play className="h-3.5 w-3.5" /> Open live command</button></div></aside>}
      </div>
      {!assistantOpen && <button onClick={() => setAssistantOpen(true)} className="fixed bottom-5 right-5 z-20 grid h-12 w-12 place-items-center bg-[#ff4757] text-white shadow-[0_10px_30px_rgba(255,71,87,.25)]"><Bot className="h-5 w-5" /></button>}
    </div></main>
}
