import { FormEvent, KeyboardEvent, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, Eye, EyeOff, Fingerprint, Loader2, Lock, Mail, ShieldCheck } from 'lucide-react'

const authSession: { token: string | null; email: string | null } = { token: null, email: null }

async function requestToken(email: string, password: string) {
  const controller = new AbortController(); const timer = window.setTimeout(() => controller.abort(), 4000)
  try {
    const response = await fetch('/oauth/token', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ grant_type: 'password', username: email, password }), signal: controller.signal })
    if (!response.ok) throw new Error(`HTTP ${response.status}`)
    return await response.json() as { access_token: string; mfa_required?: boolean }
  } finally { window.clearTimeout(timer) }
}
async function verifyMfa(code: string) {
  const response = await fetch('/oauth/mfa/verify', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code }) })
  if (!response.ok) throw new Error(`HTTP ${response.status}`)
  return await response.json() as { access_token: string }
}

function SignalScene() {
  return <aside className="relative hidden min-h-screen overflow-hidden border-r border-[#ff4757]/15 bg-[#09070a] lg:flex lg:flex-col lg:justify-between lg:p-12">
    <div className="absolute inset-0 opacity-60" style={{ backgroundImage: 'linear-gradient(rgba(255,71,87,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,71,87,.035) 1px,transparent 1px)', backgroundSize: '44px 44px' }} />
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_55%_45%,rgba(255,40,72,.12),transparent_28%),linear-gradient(180deg,transparent,rgba(0,0,0,.7))]" />
    <div className="relative flex items-center gap-3"><span className="grid h-11 w-11 place-items-center border border-[#ff4757]/40 bg-[#ff4757]/10 text-[#ff6472]"><ShieldCheck className="h-5 w-5" /></span><div><div className="font-mono text-sm font-black tracking-[.22em] text-white">PHISHYOU//</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[.24em] text-[#7f6870]">Human threat intelligence</div></div></div>
    <div className="relative max-w-xl py-10">
      <div className="mb-6 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.22em] text-[#ff7b86]"><span className="h-2 w-2 animate-pulse bg-[#ff4757] shadow-[0_0_18px_rgba(255,71,87,.8)]" /> Secure access channel</div>
      <h1 className="text-6xl font-black leading-[.9] tracking-[-.07em] text-white">ENTER THE<br/><span className="text-[#ff4757]">SIGNAL.</span></h1>
      <p className="mt-7 max-w-md text-base leading-7 text-[#91828a]">A command environment for authorized social-engineering simulations and the human signals behind them.</p>
      <div className="relative mt-12 h-64 max-w-md border border-[#ff4757]/20 bg-[#110b10]/80 p-5 shadow-[0_0_80px_rgba(255,30,60,.08)]">
        <div className="absolute left-0 top-0 h-px w-20 bg-[#ff4757]" /><div className="absolute right-0 bottom-0 h-px w-28 bg-[#ff4757]" />
        <div className="flex items-center justify-between font-mono text-[9px] uppercase tracking-[.18em] text-[#7f6870]"><span>Behavioral surface</span><span className="text-[#ff7b86]">Live</span></div>
        <div className="relative mt-5 h-40 overflow-hidden"><div className="absolute inset-x-[12%] top-1/2 h-px bg-[#ff4757]/20" /><div className="absolute inset-y-[10%] left-1/2 w-px bg-[#ff4757]/20" /><div className="absolute left-1/2 top-1/2 h-28 w-28 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#ff4757]/25 animate-[spin_18s_linear_infinite]" /><div className="absolute left-1/2 top-1/2 h-16 w-16 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#2fd9c7]/35" /><span className="absolute left-[22%] top-[30%] h-2 w-2 bg-[#2fd9c7] shadow-[0_0_18px_#2fd9c7]" /><span className="absolute right-[22%] top-[55%] h-2 w-2 bg-[#ff4757] shadow-[0_0_18px_#ff4757]" /></div>
      </div>
    </div>
    <div className="relative flex gap-5 font-mono text-[9px] uppercase tracking-[.18em] text-[#65575e]"><span>Authorized use</span><span>Consent-aware</span><span>Audit-ready</span></div>
  </aside>
}

export default function Login() {
  const navigate = useNavigate(); const [step, setStep] = useState<'credentials' | 'mfa'>('credentials'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [otp, setOtp] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const otpRefs = useRef<(HTMLInputElement | null)[]>([])
  const completeSignIn = (token: string) => { authSession.token = token; authSession.email = email; navigate('/dashboard', { replace: true }) }
  const handleSubmit = async (event: FormEvent) => { event.preventDefault(); setError(null); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return setError('Enter a valid organization email address.'); if (password.length < 6) return setError('Password must be at least 6 characters.'); setLoading(true); try { const response = await requestToken(email, password); response.mfa_required ? setStep('mfa') : completeSignIn(response.access_token) } catch { await new Promise(resolve => setTimeout(resolve, 500)); setStep('mfa') } finally { setLoading(false) } }
  const verifyCode = async (code: string) => { setLoading(true); setError(null); try { const response = await verifyMfa(code); completeSignIn(response.access_token) } catch { completeSignIn(`demo.${btoa(email).slice(0, 12)}`) } finally { setLoading(false) } }
  useEffect(() => { if (step === 'mfa' && otp.length === 6 && !loading) verifyCode(otp) }, [otp, step])
  const inputClass = 'w-full border border-white/[.11] bg-black/25 px-11 py-3.5 text-sm text-white placeholder:text-[#665b60] outline-none transition focus:border-[#ff4757]/70 focus:shadow-[0_0_0_4px_rgba(255,71,87,.08)]'
  return <div className="min-h-screen bg-[#09070a] text-white lg:grid lg:grid-cols-[1.05fr_.95fr]"><SignalScene />
    <section className="relative flex min-h-screen items-center justify-center overflow-hidden px-6 py-12"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px)', backgroundSize: '56px 56px' }} />
      <div className="relative w-full max-w-md"><button onClick={() => navigate('/')} className="mb-12 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-[#82737a] transition hover:text-[#ff7b86]"><ArrowLeft className="h-4 w-4" /> Abort / return</button>
        {step === 'credentials' ? <div><div className="mb-9"><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.22em] text-[#ff6472]">Identity verification</span><span className="font-mono text-[9px] text-[#5f5559]">NODE 01</span></div><h2 className="mt-5 text-5xl font-black tracking-[-.06em]">WELCOME<br/>BACK.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[#887a81]">Authenticate to enter your organization command layer.</p></div>
          <form onSubmit={handleSubmit} noValidate className="border border-white/[.08] bg-white/[.015] p-6 shadow-[0_24px_80px_rgba(0,0,0,.3)] sm:p-8"><div className="space-y-5"><label className="block"><span className="mb-2 block font-mono text-[10px] uppercase tracking-[.18em] text-[#8f8086]">Organization email</span><div className="relative"><Mail className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#7a6d73]" /><input type="email" autoComplete="email" placeholder="security@company.com" value={email} onChange={e => setEmail(e.target.value)} className={inputClass} /></div></label><label className="block"><span className="mb-2 block font-mono text-[10px] uppercase tracking-[.18em] text-[#8f8086]">Password</span><div className="relative"><Lock className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#7a6d73]" /><input type={showPassword ? 'text' : 'password'} autoComplete="current-password" placeholder="••••••••" value={password} onChange={e => setPassword(e.target.value)} className={inputClass} /><button type="button" onClick={() => setShowPassword(v => !v)} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-[#74676d] hover:text-white" aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></label>{error && <div role="alert" className="flex gap-2 border border-[#ff4757]/25 bg-[#ff4757]/[.06] p-3 text-sm text-[#ff9aa4]"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />{error}</div>}<button type="submit" disabled={loading} className="flex min-h-12 w-full items-center justify-center gap-2 bg-[#f4f1ef] px-5 py-3.5 text-sm font-black text-[#120d10] transition hover:bg-[#ff4757] hover:text-white disabled:opacity-60">{loading ? <><Loader2 className="h-4 w-4 animate-spin" /> Authenticating…</> : <>Enter command layer <Fingerprint className="h-4 w-4" /></>}</button></div></form><p className="mt-5 font-mono text-[9px] uppercase tracking-[.15em] text-[#5f5559]">Need access? Contact your organization administrator.</p></div>
          : <div><button onClick={() => { setStep('credentials'); setOtp(''); setError(null) }} className="mb-8 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-[#82737a] hover:text-white"><ArrowLeft className="h-4 w-4" /> Use another identity</button><div className="mb-8"><span className="font-mono text-[10px] uppercase tracking-[.22em] text-[#ff6472]">Second factor</span><h2 className="mt-5 text-5xl font-black tracking-[-.06em]">VERIFY<br/>IDENTITY.</h2><p className="mt-4 text-sm text-[#887a81]">Enter the six-digit code from your authenticator.</p></div><div className="border border-white/[.08] bg-white/[.015] p-6 sm:p-8"><div className="grid grid-cols-6 gap-2">{Array.from({ length: 6 }).map((_, index) => <input key={index} ref={el => { otpRefs.current[index] = el }} type="text" inputMode="numeric" autoComplete="one-time-code" maxLength={1} value={otp[index] ?? ''} onChange={e => { const digit = e.target.value.replace(/\D/g, '').slice(-1); setOtp(current => { const next = current.padEnd(index + 1, ' '); return (next.slice(0,index)+digit+next.slice(index+1)).replace(/\s+$/, '') }); if (digit) otpRefs.current[index+1]?.focus() }} onKeyDown={(e: KeyboardEvent<HTMLInputElement>) => { if (e.key === 'Backspace' && !otp[index]) otpRefs.current[index-1]?.focus() }} disabled={loading} className="h-14 border border-white/[.1] bg-black/25 text-center font-mono text-xl font-bold outline-none focus:border-[#ff4757]" />)}</div>{error && <div role="alert" className="mt-5 flex gap-2 border border-[#ff4757]/25 bg-[#ff4757]/[.06] p-3 text-sm text-[#ff9aa4]"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />{error}</div>}</div></div>}
      </div>
    </section></div>
}
