import { useEffect, useState } from 'react';
import { Bot, CheckCircle2, Database, Mail, RefreshCw, Save, ShieldCheck } from 'lucide-react';
import { fetchAIConfig, saveAIConfig, testAIConnection, type AIConfig } from '../services/ai';
import { fetchDBConfig, saveDBConfig, testDBConnection, type DBConfig } from '../services/db';
import { fetchEmailConfig, saveEmailConfig, testEmailConnection, type EmailConfig } from '../services/email';

const input = 'w-full rounded-xl border border-[#2D3748] bg-[#1D232D] px-3 py-2.5 text-sm text-white outline-none focus:border-[#2FD9C7] focus:ring-2 focus:ring-[#2FD9C7]/20';
const button = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-[#3D4860] bg-[#2D3748] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#232D39] disabled:opacity-50';
const primary = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#2FD9C7] px-4 py-2.5 text-sm font-bold text-[#0F1219] disabled:opacity-50';

export default function ToolSettings() {
  const [ai, setAi] = useState<AIConfig>({ provider: '', model: '', endpoint: '', apiKey: '' });
  const [db, setDb] = useState<DBConfig>({ type: '', host: '', port: 5432, database: '', username: '', password: '', ssl: false });
  const [email, setEmail] = useState<EmailConfig>({ smtp: { host: '', port: 587, secure: false, user: '', pass: '', from: '', replyTo: '' }, imap: { host: '', port: 993, secure: true, user: '', pass: '', mailbox: 'INBOX' } });
  const [status, setStatus] = useState<Record<string, string>>({});

  useEffect(() => {
    void Promise.all([fetchAIConfig(), fetchDBConfig(), fetchEmailConfig()]).then(([a, d, e]) => {
      setAi((value) => ({ ...value, provider: a.provider ?? '', model: a.model ?? '', endpoint: a.endpoint ?? '' }));
      setDb((value) => ({ ...value, type: d.type ?? '', host: d.host ?? '', port: d.port ?? 5432, database: d.database ?? '', username: d.username ?? '', ssl: d.ssl }));
      setEmail((value) => ({ smtp: { ...value.smtp, host: e.smtp.host ?? '', port: e.smtp.port, user: e.smtp.user ?? '', from: e.smtp.from ?? '', replyTo: e.smtp.replyTo ?? '', secure: e.smtp.secure }, imap: { ...value.imap, host: e.imap.host ?? '', port: e.imap.port, user: e.imap.user ?? '', mailbox: e.imap.mailbox, secure: e.imap.secure } }));
    }).catch(() => undefined);
  }, []);

  async function run(label: string, action: () => Promise<unknown>) {
    try { await action(); setStatus((value) => ({ ...value, [label]: 'Saved' })); }
    catch (error) { setStatus((value) => ({ ...value, [label]: error instanceof Error ? error.message : 'Request failed' })); }
  }

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8 space-y-6">
      <header><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#2FD9C7]">Tool Settings</p><h1 className="mt-2 text-3xl font-black tracking-tight text-white">Configure the three agent connectors.</h1><p className="mt-2 text-sm text-[#8c949f]">Only Database, LLM, and Email are exposed here. Credentials stay server-side.</p></header>

      <section id="database" className="rounded-2xl border border-[#2D3748] bg-[#15191F] p-5 sm:p-6"><div className="flex items-center gap-3"><Database className="h-5 w-5 text-[#2FD9C7]"/><div><h2 className="text-xl font-bold text-white">Database</h2><p className="text-xs text-[#7A8595]">Campaign state, messages, and audit records.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><select className={input} value={db.type} onChange={(e) => setDb({ ...db, type: e.target.value as DBConfig['type'], port: e.target.value === 'sqlite' ? null : db.port ?? 5432 })}><option value="">Select type</option><option value="postgresql">PostgreSQL</option><option value="sqlite">SQLite</option></select><input className={input} value={db.type === 'sqlite' ? db.database : db.host} onChange={(e) => setDb({ ...db, ...(db.type === 'sqlite' ? { database: e.target.value } : { host: e.target.value }) })} placeholder={db.type === 'sqlite' ? 'Database file path' : 'Host'}/>{db.type !== 'sqlite' && <><input className={input} type="number" value={db.port ?? ''} onChange={(e) => setDb({ ...db, port: Number(e.target.value) || null })} placeholder="5432"/><input className={input} value={db.database} onChange={(e) => setDb({ ...db, database: e.target.value })} placeholder="Database name"/><input className={input} value={db.username} onChange={(e) => setDb({ ...db, username: e.target.value })} placeholder="Username"/><input className={input} type="password" value={db.password} onChange={(e) => setDb({ ...db, password: e.target.value })} placeholder="Password"/></>}</div><div className="mt-5 flex flex-wrap gap-3"><button className={primary} onClick={() => void run('db-save', () => saveDBConfig(db))}><Save className="h-4 w-4"/>Save</button><button className={button} onClick={() => void run('db-test', () => testDBConnection())}><RefreshCw className="h-4 w-4"/>Test</button>{status['db-save'] === 'Saved' && <span className="inline-flex items-center gap-2 text-xs text-[#06D369]"><CheckCircle2 className="h-4 w-4"/>Saved</span>}</div></section>

      <section id="llm" className="rounded-2xl border border-[#2D3748] bg-[#15191F] p-5 sm:p-6"><div className="flex items-center gap-3"><Bot className="h-5 w-5 text-[#2FD9C7]"/><div><h2 className="text-xl font-bold text-white">LLM</h2><p className="text-xs text-[#7A8595]">The brain of the campaign agent.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className={input} value={ai.provider} onChange={(e) => setAi({ ...ai, provider: e.target.value })} placeholder="Provider"/><input className={input} value={ai.model} onChange={(e) => setAi({ ...ai, model: e.target.value })} placeholder="Model"/><input className={input} value={ai.endpoint} onChange={(e) => setAi({ ...ai, endpoint: e.target.value })} placeholder="Endpoint"/><input className={input} type="password" value={ai.apiKey} onChange={(e) => setAi({ ...ai, apiKey: e.target.value })} placeholder="API key"/></div><div className="mt-5 flex flex-wrap gap-3"><button className={primary} onClick={() => void run('ai-save', () => saveAIConfig(ai))}><Save className="h-4 w-4"/>Save</button><button className={button} onClick={() => void run('ai-test', () => testAIConnection())}><RefreshCw className="h-4 w-4"/>Test</button>{status['ai-save'] === 'Saved' && <span className="inline-flex items-center gap-2 text-xs text-[#06D369]"><CheckCircle2 className="h-4 w-4"/>Saved</span>}</div></section>

      <section id="email" className="rounded-2xl border border-[#2D3748] bg-[#15191F] p-5 sm:p-6"><div className="flex items-center gap-3"><Mail className="h-5 w-5 text-[#2FD9C7]"/><div><h2 className="text-xl font-bold text-white">Email</h2><p className="text-xs text-[#7A8595]">SMTP sends simulation emails; IMAP receives target replies.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className={input} value={email.smtp.host} onChange={(e) => setEmail({ ...email, smtp: { ...email.smtp, host: e.target.value } })} placeholder="SMTP host"/><input className={input} type="number" value={email.smtp.port} onChange={(e) => setEmail({ ...email, smtp: { ...email.smtp, port: Number(e.target.value) || 587 } })} placeholder="SMTP port"/><input className={input} value={email.smtp.user} onChange={(e) => setEmail({ ...email, smtp: { ...email.smtp, user: e.target.value } })} placeholder="SMTP username"/><input className={input} type="password" value={email.smtp.pass} onChange={(e) => setEmail({ ...email, smtp: { ...email.smtp, pass: e.target.value } })} placeholder="SMTP password"/><input className={input} value={email.smtp.from} onChange={(e) => setEmail({ ...email, smtp: { ...email.smtp, from: e.target.value } })} placeholder="From address"/><input className={input} value={email.smtp.replyTo} onChange={(e) => setEmail({ ...email, smtp: { ...email.smtp, replyTo: e.target.value } })} placeholder="Reply-To / monitored mailbox"/><input className={input} value={email.imap.host} onChange={(e) => setEmail({ ...email, imap: { ...email.imap, host: e.target.value } })} placeholder="IMAP host"/><input className={input} type="number" value={email.imap.port} onChange={(e) => setEmail({ ...email, imap: { ...email.imap, port: Number(e.target.value) || 993 } })} placeholder="IMAP port"/><input className={input} value={email.imap.user} onChange={(e) => setEmail({ ...email, imap: { ...email.imap, user: e.target.value } })} placeholder="IMAP username"/><input className={input} type="password" value={email.imap.pass} onChange={(e) => setEmail({ ...email, imap: { ...email.imap, pass: e.target.value } })} placeholder="IMAP password"/></div><div className="mt-5 flex flex-wrap gap-3"><button className={primary} onClick={() => void run('email-save', () => saveEmailConfig(email))}><Save className="h-4 w-4"/>Save</button><button className={button} onClick={() => void run('email-test', () => testEmailConnection())}><ShieldCheck className="h-4 w-4"/>Test SMTP + IMAP</button>{status['email-save'] === 'Saved' && <span className="inline-flex items-center gap-2 text-xs text-[#06D369]"><CheckCircle2 className="h-4 w-4"/>Saved</span>}</div></section>
    </div>
  );
}
